todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    task_complete,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/complete", task_complete, name="task-complete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag-delete"),

]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    class Meta:
        ordering = ["is_completed", "-date_of_creation"]

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from django.contrib.auth import get_user_model

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Task
        fields = (
            "name",
            "content",
            "deadline",
            "tags"
        )

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


def task_complete(request, pk) -> HttpResponseRedirect:
    task = Task.objects.get(id=pk)
    task.is_completed = not task.is_completed
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>TODO list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
<div>
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}
            {% endblock %}

            {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previouse_page_number }}" class="page-link"><<</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">>></a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>
    Tags
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'todo:tag-update' tag.id %}" class="btn btn-secondary">Update</a></td>
        <td><a href="{% url 'todo:tag-delete' tag.id %}" class="btn btn-secondary">Delete</a></td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    <p>There are no task types.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
  <p><a href="{% url 'todo:tag-create' %}" class="btn btn-secondary">Create new tag</a></p>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>TODO list
  <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
    Add task
  </a>
  </h1>
  <br>
  {% if task_list %}
    {% for task in task_list %}
      <h4>
        <strong>{{ task }}
        {% if task.is_completed %}
          <a href="{% url 'todo:task-complete' task.id %}" class="btn btn-secondary link-to-page">Undo</a>
          <p class="text-success" style="display: inline">Done</p>
        {% else %}
          <a href="{% url 'todo:task-complete' task.id %}" class="btn btn-success link-to-page">Complete this task</a>
          <p class="text-danger" style="display: inline">Not done</p>
        {% endif %}
        </strong>
      </h4>
      <p style="display: inline">
        Created: {{ task.date_of_creation }}
      </p>
        {% if task.deadline %}
          <p style="display: inline;color: brown">Deadline: {{ task.deadline }}</p>
        {% endif %}

      <h4>
        Tags:
        {% for tag in task.tags.all %}
        {{ tag }}
        {% endfor %}
        <a href="{% url 'todo:task-update' task.id %}">Update</a>
        <a href="{% url 'todo:task-delete' task.id %}">Delete</a>
      </h4>
      <hr>
    {% endfor %}
  {% else %}
    <p>There are no task.</p>
  {% endif %}
{% endblock %}